events {}

http {
    server {
        listen 80;
        index index.html;
        server_name localhost;
        root /var/www/html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
